build: add self-built runner for macos x64

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,16 +17,15 @@ jobs:
       fail-fast: false
       matrix:
         include:
-          # - runner: ubuntu-22.04
-          #   arch: x64
-          #   conan_arch: x86_64
-
           # - runner: [self-hosted, Linux, X64, taosgen]
           #   arch: x64
           #   conan_arch: x86_64
-          - runner: [self-hosted, Linux, ARM64, taosgen]
-            arch: arm64
-            conan_arch: armv8
+          # - runner: [self-hosted, Linux, ARM64, taosgen]
+          #   arch: arm64
+          #   conan_arch: armv8
+          - runner: [self-hosted, macOS, X64, taosgen]
+            arch: x64
+            conan_arch: x86_64
 
     runs-on: ${{ matrix.runner }}
 
@@ -96,9 +95,10 @@ jobs:
         run: |
           mkdir -p ~/.tdengine-cache
           cd ~/.tdengine-cache
+          arch="${{ matrix.arch }}"
+          version="${{ steps.get_td_version.outputs.version }}"
+
           if [ "${{ runner.os }}" = "Linux" ]; then
-            arch="${{ matrix.arch }}"
-            version="${{ steps.get_td_version.outputs.version }}"
             pkg="tdengine-tsdb-enterprise-${version}-linux-${arch}.tar.gz"
 
             # Clean up old packages
@@ -113,7 +113,7 @@ jobs:
             done
 
             # Download if not exists
-            url="https://downloads.taosdata.com/tdengine-tsdb-enterprise/${version}/${pkg}"
+            url="http://192.168.1.131/data/nas/TDengine/3.3/v${version}/enterprise/${pkg}"
             if [ -f "$pkg" ] && [ $(stat -c%s "$pkg") -gt $((300*1024*1024)) ]; then
               echo "$pkg already exists and is larger than 300MB, skip download."
             else
@@ -124,7 +124,30 @@ jobs:
             ls -al
 
           elif [ "${{ runner.os }}" = "macOS" ]; then
-            echo "TODO: macOS download logic"
+            version ="3.3.8.1"
+            pkg="tdengine-tsdb-oss-${version}-macos-${arch}.pkg"
+
+            # Clean up old packages
+            pwd
+            ls -al
+            for f in tdengine-tsdb-oss-*-macos-*.pkg; do
+              [ -e "$f" ] || continue
+              if [ "$f" != "$pkg" ]; then
+                echo "Deleting old package: $f"
+                rm -f "$f"
+              fi
+            done
+
+            # Download if not exists
+            url="http://192.168.1.131/data/nas/TDengine/3.3/v${version}/community/${pkg}"
+            if [ -f "$pkg" ] && [ $(stat -f%z "$pkg") -gt $((100*1024*1024)) ]; then
+              echo "$pkg already exists and is larger than 100MB, skip download."
+            else
+              echo "Download URL: $url"
+              curl -fSL "$url" -o "$pkg"
+            fi
+            pwd
+            ls -al
           fi
 
       - name: Install & Start TDengine
@@ -153,7 +176,16 @@ jobs:
             taos -V
 
           elif [ "${{ runner.os }}" = "macOS" ]; then
-            echo "TODO: macOS extract logic"
+            pkg="tdengine-tsdb-oss-${version}-macos-${arch}.pkg"
+            pwd
+            ls -al
+            # Install
+            sudo installer -pkg "$pkg" -target /
+            # Start TDengine
+            sudo taosd &
+            sudo taosadapter &
+            # Verify installation
+            taos -V || true
           fi
 
       - name: Checkout taosgen code
@@ -234,6 +266,5 @@ jobs:
         run: cmake --build . --config Debug -j $(nproc || sysctl -n hw.ncpu)
 
       - name: Test
-        if: runner.os == 'Linux'
         working-directory: build
         run: ctest --output-on-failure --verbose
